package codegenerate

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"

	"github.com/Masterminds/sprig/v3"
)

func GenerateFromTemplate(source, destination string, data any) error {
	name := filepath.Base(source)

	template, err := template.New(name).Funcs(sprig.TxtFuncMap()).ParseFiles(source)
	if err != nil {
		return err
	}

	buffer := &bytes.Buffer{}
	if _, err := fmt.Fprintf(buffer, "// Code generated by %s; DO NOT EDIT.\n", name); err != nil {
		return err
	}
	if err := template.Execute(buffer, data); err != nil {
		return err
	}

	code, err := format.Source(buffer.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(destination, code, 0666)
}
